# Generated by Django 2.2.4 on 2019-08-15 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Avenue')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=50, verbose_name='Commune')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Province')),
                ('country', models.CharField(default='R.D. Congo', max_length=50, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('english_name', models.CharField(max_length=100, verbose_name='Nom Anglais')),
                ('french_name', models.CharField(max_length=100, verbose_name='Nom Français')),
                ('local_name', models.CharField(max_length=100, verbose_name='Nom Locale')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('region', models.CharField(max_length=100, verbose_name='Region du Globe')),
                ('continent', models.CharField(max_length=50, verbose_name='Continent')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('date_registered', models.DateField(blank=True, null=True, verbose_name="Date d'Enregistrement")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentDestinataire',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='destinataire_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentOwner',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ship_owner_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Date de Départ')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name="Date d'Arrivée")),
                ('point_of_shipping', models.CharField(blank=True, max_length=200, null=True, verbose_name='Point de Départ')),
                ('point_of_arrival', models.CharField(blank=True, max_length=200, null=True, verbose_name="Point d'Arrivée")),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_content_type', to='contenttypes.ContentType')),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_movement_destinataire', to='shipping_management.ShipmentDestinataire')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_movement_shipment', to='shipping_management.Shipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_shipment_owner', to='shipping_management.ShipmentOwner'),
        ),
        migrations.CreateModel(
            name='IndividualShipMaster',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ind_ship_master_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ind_ship_master_location', to='shipping_management.Address', verbose_name='Dépôts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessShipMaster',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bus_ship_master_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'entreprise")),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_ship_master_location', to='shipping_management.Address', verbose_name='Dépôts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
